name: Publish NuGet to GitHub Packages

on:
  push:
    branches:
        - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write # Grant write permission for packages
      contents: read  # Grant read permission for repository contents

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # Or your desired .NET version

    - name: Build and Pack
      run: |
        dotnet build --configuration Release
        dotnet pack --configuration Release --no-build --output ./package-output

    - name: Push to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        dotnet nuget push "./package-output/*.nupkg" \
          --source "https://nuget.pkg.github.com/itshubert/index.json" \
          --api-key $GITHUB_TOKEN \
          --skip-duplicate